### ISSUE TITLE
Design issues of the gnn model

### ISSUE THREAD

**Issue by 464hee** [engrodawood/HiGGsXplore#1]
/main/workspace/model/gnn.py
In line 121 of the code:
                #x = self.first_h(x)
You canceled the downscaling of features, won't this operation make your graphics card cause a memory overflow?
Your features are 1024, if it is a higher number of features, for example 2048, 4096, then it may not be possible to run the network
What do you think about this? @engrodawood

**Comment by engrodawood** [comment]
Hi, 

Thank you for raising this. In my case the feature vector size was not that big 1024, and I was able to fit that into the GPU memory. But you are right as the node level feature vector size increases the downscaling may be needed. In that case the #x = self.first_h(x) need to be uncommented. 

thanks.
